### PR TITLE
Update scryfall.py

### PR DESCRIPTION
**Pull request by augustot2**
added a multilanguage search, please consider it for worldwide players ;)

### CODE REVIEW

**Comment by augustot2** [comment]
Hi oliver, me and my friends love magic and found your bot really useful, but they wanted to search in portuguese too, so I modified this line so We could search both in portuguese (Brazil) and english

**Comment by OliverHofkens** [comment]
Hey @augustot2, sorry for the late reply, I never got a notification from Github!
Thank you for this PR, I'll happily accept it.

1 quick note though, @ScryfallBot is now powered by this spiritual successor: [scryfall-telegram-rs-serverless](https://github.com/OliverHofkens/scryfall-telegram-rs-serverless). I'll add your change there as well and re-deploy the bot!

**Comment by OliverHofkens** [comment]
@augustot2 I've added your change to the other repository as well here: https://github.com/OliverHofkens/scryfall-telegram-rs-serverless/commit/1310bd3201b9efb00f1ee37ab431068d6c54198e

The changes are now live and seem to work:
Screenshot 2020-03-25 at 14 13 24
Screenshot 2020-03-25 at 14 13 46

Thanks for your contribution!

**Comment by augustot2** [comment]
Thanks Man, me and my friends will use this for playing during the
quarantine here in Brazil!

Best regards,
Augusto Ferrari

**Pull request merged**
